/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = [".media[_ngcontent-%COMP%] {\n    margin-bottom: 30px;\n}"];
export { styles as styles };
//# sourceMappingURL=app.component.css.shim.ngstyle.js.map